run:
  concurrency: 4
  tests: false
  skip-files:
    - ".*_mock\\.go$"

linters:
  disable-all: true
  enable:
    - unused
    - errcheck
    - govet
    - staticcheck
    - bodyclose
    - dogsled
    - dupl
    - exportloopref
    - gocognit
    - goconst
    - gofmt
    - gosec
    - tagliatelle
    - whitespace
    - depguard
    - gosimple
    - stylecheck
    - unconvert
